from skrl.utils.other_model_instantiators.torch.lstm_deterministic import LSTMDeterministic
from skrl.utils.other_model_instantiators.torch.lstm_gaussian import LSTMGaussian
from skrl.utils.other_model_instantiators.torch.lstm_shared import LSTMShared
from skrl.utils.other_model_instantiators.torch.mlp_shared_chunked import MLPShared